name: Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-central1
  SERVICE: cloud-run-svc
  GAR_REPO: docker-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Authentication using Service Account Key ---
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CICD_SVC_ACCT_PK }} # Use the secret containing your SA key JSON
      # --------------------------------------------

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        # project_id and other args might be needed here depending on setup,
        # but often credentials_json handles default project config

      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPO}/${SERVICE}:${{ github.sha }} .
          docker push ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${GAR_REPO}/${SERVICE}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.GAR_LOCATION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show deployed service URL
        run: echo ${{ steps.deploy.outputs.url }}
